---
title: "Sales Report"
author: "Abubakar Shola Suleiman"
date: "9/7/2022"
output:
  pdf_document:
    toc: yes
    toc_depth: '2'
  html_document:
    code_folding: none
    df_print: paged
    highlight: tango
    number_sections: yes
    theme: flatly
    toc: yes
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo = TRUE,
    eval = TRUE,
    message = FALSE,
    warning = FALSE,
    dpi = 300,
    fig.align = "center"
    )

# See Options: knitr::opts_chunk$get()
```

```{r, echo=FALSE}
# Load Libraries
library(tidyverse)
library(plotly)
library(lubridate)
library(plotly)
```





```{r, echo=FALSE}
# Importing data set
bikes_tbl      <- readRDS("../00_bike_data/bikes_tbl.rds")
bikeshops_tbl  <- readRDS("../00_bike_data/bikeshops_tbl.rds")
orderlines_tbl <- readRDS("../00_bike_data/orderlines_tbl.rds")

bike_orderlines_tbl <- orderlines_tbl %>%
    left_join(bikes_tbl,     by = c("product_id" = "bike_id")) %>%
    left_join(bikeshops_tbl, by = c("customer_id" = "bikeshop_id")) %>%
    mutate(total_price = price_euro * quantity)

#bike_orderlines_tbl
```



```{r, echo=FALSE}
# Formatting
format_to_euro <- function(x, suffix = " ...") {

  scales::dollar(x,
                 suffix       = suffix,
                 prefix       = "",
                 big.mark     = ".",
                 decimal.mark = ",")
}

euro_format <- function(scale        = 1,
                        prefix       = "",
                        suffix       = " ...",
                        big.mark     = ".",
                        decimal.mark = ",") {

  scales::dollar_format(suffix       = suffix,
                        prefix       = prefix,
                        big.mark     = big.mark,
                        decimal.mark = decimal.mark,
                        scale        = scale)

}

```
# Total Sales Charts
## Quarterly Sales Trends
```{r, echo=FALSE}

#Selecting on the needed data...QUARTER
total_sales_q_tbl <- bike_orderlines_tbl %>%

  select(order_date, total_price) %>%

  mutate(date_rounded = floor_date(order_date, unit = "quarter")) %>%

  group_by(date_rounded) %>%
  summarise(total_sales = sum(total_price)) %>%
  ungroup() %>%

  mutate(label_text = str_glue("Sales: {format_to_euro(total_sales)}
                                 Date: {date_rounded %>% format('%B %Y')}"))

#total_sales_q_tbl

```


```{r, echo=FALSE}
g1 <- total_sales_q_tbl %>%
  ggplot(aes(x = date_rounded, y = total_sales)) +

  # Geoms
  geom_point() +
  geom_smooth(method = "loess", span = 0.2) +

  # Formatting
  
  # Convert scale to euro format
  scale_y_continuous(labels = euro_format()) +
  
  # Make sure 0 will always be shown (even if the data is far away)
  expand_limits(y = 0) +
  
  labs(
    title = "Total Sales",
    y = "Revenue (EUR)",
    x = ""
  )

g1

```



## Monthly Sales Trends

```{r, echo=FALSE}

#Selecting on the needed data...MONTH
total_sales_m_tbl <- bike_orderlines_tbl %>%

  select(order_date, total_price) %>%

  mutate(date_rounded = floor_date(order_date, unit = "month")) %>%

  group_by(date_rounded) %>%
  summarise(total_sales = sum(total_price)) %>%
  ungroup() %>%

  mutate(label_text = str_glue("Sales: {format_to_euro(total_sales)}
                                 Date: {date_rounded %>% format('%B %Y')}"))

#total_sales_m_tbl

```




```{r, echo=FALSE}
g2 <- total_sales_m_tbl %>%
  ggplot(aes(x = date_rounded, y = total_sales)) +

  # Geoms
  geom_point() +
  geom_smooth(method = "loess", span = 0.2) +

  # Formatting
  
  # Convert scale to euro format
  scale_y_continuous(labels = euro_format()) +
  
  # Make sure 0 will always be shown (even if the data is far away)
  expand_limits(y = 0) +
  
  labs(
    title = "Total Sales",
    y = "Revenue (EUR)",
    x = ""
  )

g2

```



## Weekly Sales Trends


```{r, echo=FALSE}

#Selecting on the needed data...
total_sales_w_tbl <- bike_orderlines_tbl %>%

  select(order_date, total_price) %>%

  mutate(date_rounded = floor_date(order_date, unit = "week")) %>%

  group_by(date_rounded) %>%
  summarise(total_sales = sum(total_price)) %>%
  ungroup() %>%

  mutate(label_text = str_glue("Sales: {format_to_euro(total_sales)}
                                 Date: {date_rounded %>% format('%B %Y')}"))

#total_sales_w_tbl

```


```{r, echo=FALSE}
g3 <- total_sales_w_tbl %>%
  ggplot(aes(x = date_rounded, y = total_sales)) +

  # Geoms
  geom_point() +
  geom_smooth(method = "loess", span = 0.2) +

  # Formatting
  
  # Convert scale to euro format
  scale_y_continuous(labels = euro_format()) +
  
  # Make sure 0 will always be shown (even if the data is far away)
  expand_limits(y = 0) +
  
  labs(
    title = "Total Sales",
    y = "Revenue (EUR)",
    x = ""
  )

g3

```




# Category Sales Charts
## Road

```{r, echo=FALSE}


plot_categories <- function(category_2 = "All",
                            unit = "month", date_format = "%B %Y",
                            ncol = 1, scales = "free_y",
                            interactive = TRUE) {

  

  data_tbl <- bike_orderlines_tbl %>%
    select(order_date, category_2, total_price) %>%
    mutate(date_rounded = floor_date(order_date, unit = unit)) %>%

    group_by(date_rounded, category_2) %>%
    summarise(total_sales = sum(total_price)) %>%
    ungroup() %>%

    mutate(label_text = str_glue("Sales: {format_to_euro(total_sales)}
                                 Date: {date_rounded %>% format(date_format)}")) %>%

    mutate(category_2 = as_factor(category_2) %>%
             fct_reorder2(date_rounded, total_sales))

  
  cat_2_text <- str_to_lower(category_2)

  
  if (cat_2_text != "all") {
    data_tbl <- data_tbl %>%
      filter(category_2 %>%
               str_to_lower() %>%
               str_detect(pattern = cat_2_text))
  }

  
  gb <- data_tbl %>%
    ggplot(aes(x = date_rounded, y = total_sales, color = category_2)) +

    
    geom_point(aes(text = label_text), color = "#2c3e50") +
    geom_smooth(method = "loess", span = 0.2) +
    facet_wrap(~ category_2, scales = scales, ncol = ncol) +

   
    expand_limits(y = 0) +
    theme(legend.position = "none",
          strip.text.x = element_text(margin = margin(5, 5, 5, 5, unit = "pt"))) +
    scale_y_continuous(labels = euro_format(scale = 1e-3, suffix = "K")) +
    labs(
      title = "Sales By Category 2",
      y = "", x = ""
    )

  
  
    return(gb)
  

}
```


### Quarterly
```{r, echo=FALSE}
plot_categories( category_2 = "(Race|Triathlon Bike|Endurance|Cyclocross)", 
                unit = "quater",
                ncol = 1, 
                scales = "free_y", 
                date_format = "%Y-%m-%d")


```

### Monthly

```{r, echo=FALSE}
plot_categories( category_2 = "(Triathlon Bike|Race|Endurance|Cyclocross)", 
                unit = "month",
                ncol = 1, 
                scales = "free_y", 
                date_format = "%Y-%m-%d")


```



### Weekly

```{r, echo=FALSE}
plot_categories(category_2 = "(Endurance|Race|Cyclocross|Triathlon Bike)", 
                unit = "week",
                ncol = 1, 
                scales = "free_y", 
                date_format = "%Y-%m-%d")


```

## Mountain
### Quarterly
```{r, echo=FALSE}
plot_categories( category_2 = "(Trail|Cross-Country|Enduro|Downhill|Fat Bikes|Dirt Jump)", 
                unit = "quater",
                ncol = 1, 
                scales = "free_y", 
                date_format = "%Y-%m-%d")


```

### Monthly

```{r, echo=FALSE}
plot_categories( category_2 = "(Trail|Cross-Country|Enduro|Downhill|Fat Bikes|Dirt Jump)", 
                unit = "month",
                ncol = 1, 
                scales = "free_y", 
                date_format = "%Y-%m-%d")


```



### Weekly

```{r, echo=FALSE}
plot_categories(category_2 = "(Cross-Country|Trail|Enduro|Dirt Jump|Downhill|Fat Bikes)", 
                unit = "week",
                ncol = 1, 
                scales = "free_y", 
                date_format = "%Y-%m-%d")


```
